### ISSUE TITLE
UML diagrams for Autolab

### ISSUE THREAD

**Issue by kashyapgajera** [AutolabJS/AutolabJS#165]
![activity submit](https://cloud.githubusercontent.com/assets/9445462/25675510/571536d8-305c-11e7-8dee-6529de95e05f.png)
![lab_query](https://cloud.githubusercontent.com/assets/9445462/25675535/70090142-305c-11e7-9959-7ba6107d1c39.png)
![save_code activity](https://cloud.githubusercontent.com/assets/9445462/25675544/7e21a95a-305c-11e7-888c-b883a3dbb53d.png)
![status](https://cloud.githubusercontent.com/assets/9445462/25675550/829efa78-305c-11e7-9d71-3acfbc033421.png)
![results](https://cloud.githubusercontent.com/assets/9445462/25697633/5a709e94-30d9-11e7-8dd2-665405c13a5c.png)

**Comment by prasadtalasila** [comment]
plant uml text files?

**Comment by prasadtalasila** [comment]
These images have been put up in [Kashyap's report](https://github.com/AutolabJS/AutolabJS/wiki/Kashyap's-Report). Closing the issue now.
