### ISSUE TITLE
IDs with 13 characters not showing up in scoreboard after submission.

### ISSUE THREAD

**Issue by ravijoshiBITS** [AutolabJS/AutolabJS#190]
I submitted code for the test lab, with an ID of 13 characters, and got 4/4 points, but the scoreboard is not showing IDs such as 2012A7PS0001G.

**Comment by prasadtalasila** [comment]
This is because of 12 character limit imposed by [main_server.js](https://github.com/AutolabJS/AutolabJS/blob/master/main_server/main_server.js#L73) while creating the marks table in the database. 

Solution: change the id_no datatype from VARCHAR to TINYTEXT.

**Comment by prasadtalasila** [comment]
@AnkshitJain 
It seems that TINYTEXT requires two memory accesses for one read of a table row. As per the advice on this [stackoverflow column](https://stackoverflow.com/questions/7295103/mysql-tinytext-vs-varchar-vs-char), it seems VARCHAR is better for a strings of less than 255 characters.

So, lets use VARCHAR(30) for id_no.

**Comment by prasadtalasila** [comment]
problem solved in merge commit bfea5bf
