### ISSUE TITLE
Pass the quality logs from execution node to the client

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#193]
The issue #192 refers to adding PMD to execution node. With the help of PMD, execution node extends the scores.json to include quality log. This quality log must be propagated via load balancer and main server to the client.

**Comment by prasadtalasila** [comment]
@AnkshitJain We can reduce the scope of this feature by simply appending the quality logs to the evaluation logs. That would not require any changes to JS files. We only need to update the Dockerfile of execution nodes and the model unit_tests of Java language.
The arrangement serves its purpose for now. What do you say to this idea?

**Comment by AnkshitJain** [comment]
The arrangement would be a temporary fix. Given that we plan to include other code quality tools in future, if the basic framework is right with PMD, it just leaves us with adding a script to check code quality for other languages as well. Also, evaluation logs should remain different from the quality logs as both serve different purposes.

**Comment by prasadtalasila** [comment]
agreed. Then back to original plan of putting everything in place at once.

**Comment by prasadtalasila** [comment]
Not a priority right now.
