### ISSUE TITLE
Change in Deployment Tests

### ISSUE THREAD

**Issue by AnkshitJain** [AutolabJS/AutolabJS#209]
The new directory structure suggested in #199 and #207 will require a different approach to validate the deployment tests.

**Comment by prasadtalasila** [comment]
Please provide more details on the issue.

**Comment by AnkshitJain** [comment]
The deployment test for an incorrect node configuration was checked for in the only deployment test in the file [execution-node.bats](https://github.com/AutolabJS/AutolabJS/blob/dev/tests/deployment_tests/execution-node.bats). It requires the shell output of the execution node, but with the suggested change in the structure, we will have 5 pre-initialsed nodes, and the shellOutput can be in any one of them. Instead the test should change to checking if all the nodes that exist in the config file, can clone a test repo from gitlab, which can ensure that their certificates have been registered with Gitlab.
