### ISSUE TITLE
Duplicate use of submit.js 

### ISSUE THREAD

**Issue by AnkshitJain** [AutolabJS/AutolabJS#210]
The submit.js file has been used in both functional tests and deployment tests. It would be appropriate if it is moved from the functional tests directory to its parent directory, where tests in both functional tests and deployment tests can use it.

**Comment by prasadtalasila** [comment]
This is a forward looking refactoring advice on a code that is not even there in the repo, not a good practice. It only increases the work in progress without moving the ship forward.

@AnkshitJain For now, it may be better to close the issue and re-open the same at the right time in future.

**Comment by AnkshitJain** [comment]
The deployment tests exist in the dev branch for now. It can be handled when the number of deployment tests increase and is not an absolute priority right now.
