### ISSUE TITLE
Duplicate installation commands in playbook.yml files and setup files

### ISSUE THREAD

**Issue by AnkshitJain** [AutolabJS/AutolabJS#222]
As suggested on #219, docker and pip installations are repeated in the yml files which is expected to be completed in setup.sh. Review the lines 7-15 of playbook-single.yml, and the lines 1-7 of playbook.yml.
wrt lines 13, 16, 17 of setup.sh

**Comment by prasadtalasila** [comment]
PR #282 removes duplication from the Ansible playbooks.
