### ISSUE TITLE
create util/logger.js module

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#234]
The logger module needs to read the configuration information from deploy/configs/util/logger.json. Each AutolabJS component shall have a role. Each AutolabJS component passes an object of the form

`{role:<component_role>, cmd:log}`

to the constructor of object exported by logger.js module. Valid values for component_role are: main_server, load_balancer, execution_node_&lt;ip&gt;_&lt;port&gt;

The suggested tests for logger.js module are:

1. Creation of logger object as per json configuration.
1. Store the log messages to designated files.
1. Store log messages with different levels to designated files.
1. Two independent logger objects can be created.
1. The independent logger objects store log messages in proper files as per their role.

**Comment by prasadtalasila** [comment]
Carry over discussion from closed PR #233.

1. If possible, lets avoid the console altogether. We can always use grep/more/tail UNIX commands to process the files. It might be better not to make the components aware of the logging strategy. Let the components feed the log to logger.js object and let logger.js log based on the logging strategy specified in logger.json.
1. It might also be better to choose different strategies and log files for different log levels. Please see the log4j conventions which helps you configure log levels and files for different logging strategies. Winston might have them too.
1. The file names can be derived from `component_role` field.

**Comment by AnkshitJain** [comment]
PR #236 completes the work described here.
