### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#239]
The keys.sh file is creating the following items in 'AutolabJS/execution_nodes' directory.
```
cleanup.sh            execute_node.js           execution_node_2          execution_node_3_csr.pem  execution_node_5          package.json
docker-entrypoint.sh  execution_node_1          execution_node_2_csr.pem  execution_node_4          execution_node_5_csr.pem  README.md
Dockerfile            execution_node_1_csr.pem  execution_node_3          execution_node_4_csr.pem  extract_run.sh            tests
```
Essentially, all the SSL certificates are being put at the top-level of `execution_nodes/` directory and are polluting the code base. Ideally, these certificates would be put in `execution_nodes/ssl/` directory. The proposed directory structure for `execution_nodes/ssl/` directory is as follows.
```
execution_node_1/  execution_node_2/  execution_node_3/  execution_node_4/  execution_node_5/
```

Also the installation setup is still heavily dependent on the files in the `~/AutolabJS/` location. It might be wise to completely copy all the required files to `/opt/autolabjs` or any other specified installation directory and then complete the installation from that location. When all the references are moved to the installation directory, the installation setup stands alone. The downloaded code from the users home directory can be completely removed and the setup would still be running properly.

At present, the volume mapping of containers use code from `~/AutolabJS/` directory, but the npm module installation happens in `/opt/autolabjs/<component-name>/node_modules` directory. The said mismatch is giving raise to the following errors in the containers.
```bash
2017-11-22T05:19:41.213318738Z Error: Cannot find module 'express'
2017-11-22T05:19:41.213323066Z     at Function.Module._resolveFilename (module.js:536:15)
2017-11-22T05:19:41.213336134Z     at Function.Module._load (module.js:466:25)
2017-11-22T05:19:41.213340476Z     at Module.require (module.js:579:17)
2017-11-22T05:19:41.213344431Z     at require (internal/module.js:11:18)
2017-11-22T05:19:41.213348275Z     at Object.<anonymous> (/main_server/main_server.js:2:15)
2017-11-22T05:19:41.213355381Z     at Module._compile (module.js:635:30)
2017-11-22T05:19:41.213362124Z     at Object.Module._extensions..js (module.js:646:10)
2017-11-22T05:19:41.213366690Z     at Module.load (module.js:554:32)
2017-11-22T05:19:41.213370751Z     at tryModuleLoad (module.js:497:12)
2017-11-22T05:19:41.213374800Z     at Function.Module._load (module.js:489:3)
2017-11-22T05:20:41.795773709Z module.js:538
2017-11-22T05:20:41.795823585Z     throw err;
2017-11-22T05:20:41.795829490Z     ^
2017-11-22T05:20:41.795834134Z 
```

@AnkshitJain please fix the installation problems (this issue and issue #237)  before you do any other code development. You should also involve Jasmeet Kaur in the process. At the very least, she can shadow you while you fix this problem so that she can get a hang of the process.

**Comment by prasadtalasila** [comment]
Another error observed is in the submission directory setting in inventory file.
```
[loadbalancer]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2 submissions_dir=../load_balancer/submissions gitlab_hostname=localhost gitlab_password=12345678
```
The submission directory would ideally point to `/opt/autolabjs/load_balancer/submissions`.

**Comment by prasadtalasila** [comment]
The keys not copied correctly for containers.
loadbalancer and mainserver needs to have their ssl keys copied to `/opt/autolab/main_server/ssl` and `/opt/autolabjs/load_balancer/ssl` directories.

**Comment by prasadtalasila** [comment]
If we go the absolute path way for the volume mappings of the containers, the following mappings should work.

loadbalancer container:
```
        volumes:
          - "/opt/autolabjs/load_balancer:/load_balancer"
          - "/opt/autolabjs/load_balancer/submissions:/load_balancer/submissions"
          - "/etc/localtime:/etc/localtime:ro"
          - "/opt/autolabjs/deploy/configs/load_balancer:/etc/load_balancer"
          - "/opt/autolabjs/deploy/keys/gitlab/load_balancer:/root/.ssh/"
          - "/opt/autolabjs/util:/util"
          - "/opt/autolabjs/deploy/configs/util:/etc/util"
```

mainserver container:
```
          - "/opt/autolabjs/main_server:/main_server"
          - "/etc/localtime:/etc/localtime:ro"
          - "/opt/autolabjs/deploy/configs/main_server:/etc/main_server"
          - "/opt/autolabjs/util:/util"
          - "/opt/autolabjs/deploy/configs/util:/etc/util"
```

executionnode1 container:
```
          - "/opt/autolabjs/execution_nodes/execution_node_1:/execution_nodes"
          - "/etc/localtime:/etc/localtime:ro"
          - "/opt/autolabjs/deploy/configs/execution_nodes/execution_node_1:/etc/execution_node"
          - "/opt/autolabjs/deploy/keys/gitlab/execution_nodes/execution_node_1:/root/.ssh/"
          - "/opt/autolabjs/util:/util"
          - "/opt/autolabjs/deploy/configs/util:/etc/util"
```

**Comment by prasadtalasila** [comment]
The following errors were reported by Ankshit Jain.

Firstly the docker building fails for no specific reason. 
```
W: The repository 'https://deb.nodesource.com/node_8.x xenial Release' does not have a Release file.
E: Failed to fetch https://deb.nodesource.com/node_8.x/dists/xenial/main/source/Sources  gnutls_handshake() failed: Error in the pull function.
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
This the error I faced when building execution_node for quite a few times, when it had already built main server and load balancer before it. Interestingly, the same file worked without any changes when run multiple times. I have been facing this issue for a while too.

Running the yml file also gives the following error:
```
PLAY [gitlab] *************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************
ok: [localhost]

TASK [Get Private Token] **************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content": "{\"error\":\"404 Not Found\"}", "content_length": "25", "content_type": "application/json", "date": "Wed, 22 Nov 2017 14:33:25 GMT", "failed": true, "json": {"error": "404 Not Found"}, "msg": "Status code was not [201]: HTTP Error 404: Not Found", "redirected": false, "server": "nginx", "status": 404, "url": "https://localhost/api/v4/session", "vary": "Origin", "x_request_id": "6e003bad-646f-4295-914e-da464cf0d6e6", "x_runtime": "0.003720"}
```

**Comment by prasadtalasila** [comment]
@AnkshitJain The node 8.x installation has been a problem for all of yesterday. I tried the same today early morning and it worked like a charm. This situation really calls for having our own docker images pushed to docker hub so that we are less dependent on the third-party libraries for every installation.

**Comment by AnkshitJain** [comment]
The same could be said for main_server and load_balancer. They both have the same commands till the error point in execution node docker files. Having said that, having our own docker images on docker hub would mean we expect users to download ~500MB image for mainserver/loadbalancer  which can be integrated as one image and used by different names, along with the execution node image which is ~1.3GB.(Values are when the images are saved on the system. Actual values may differ) We do not want our installation to fail because of third party errors but having to download additional 2GB would be another network constraint. What should be our tradeoff here?
If the images are build on the system, it requires 100MB for the ubuntu image, and close to 100 MB for additional downloads for main server/load_balancer. For the execution node that goes up by a roughly 200MB more. 
In this case what can be the optimal approach?

**Comment by prasadtalasila** [comment]
@AnkshitJain The gitlab version has changed from 10.1.0 to 10.2.0. The Gitlab v3 API we are using in ansible playbook might have been removed completely from the latest version. We have to migrate all the Gitlab APIs in the playbooks to Gitlab v4 API.

**Comment by prasadtalasila** [comment]
It's better to move the MySQL DB username and password credentials from AutolabJS config to Ansible variable files.

**Comment by prasadtalasila** [comment]
Installation errors have been fixed. Refactoring of AutolabJS config shall be attempted later.
