### ISSUE TITLE
Load balancer error when shell output during evaluation is very large

### ISSUE THREAD

**Issue by AnkshitJain** [AutolabJS/AutolabJS#259]
This case was observed in the following scenario:

An evaluation request is made which results is an exception. The log file generated is around 2000 lines. 
We expect the log file to be limited to 50 lines only. As it is done [here](https://github.com/AutolabJS/AutolabJS/blob/master/docs/examples/unit_tests/execute.sh#L250) and [here](https://github.com/AutolabJS/AutolabJS/blob/master/docs/examples/io_tests/execute.sh#L239).

This checks for the log.txt generated. However we miss the case where the shell out is greater than 50 lines and in return shellOut.txt is very large. This file is directly copied to the log file log.txt and we end up with a very large log file. Now, execution node does not bother about it, happily sends it to the load balancer, where the modules used by the load balancer fail, which  results in the execution node not returned to the node_queue. 

The load balancer gives the following message and the client faces a stuck evaluation with no response. 
`````
Error: request entity too large
    at makeError (/load_balancer/node_modules/raw-body/index.js:184:15)
    at module.exports (/load_balancer/node_modules/raw-body/index.js:40:15)
    at read (/load_balancer/node_modules/body-parser/lib/read.js:62:3)
    at jsonParser (/load_balancer/node_modules/body-parser/lib/types/json.js:87:5)
    at Layer.handle [as handle_request] (/load_balancer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/load_balancer/node_modules/express/lib/router/index.js:317:13)
    at /load_balancer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/load_balancer/node_modules/express/lib/router/index.js:335:12)
    at next (/load_balancer/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/load_balancer/node_modules/body-parser/lib/types/urlencoded.js:72:36)
`````

The simpler approach would be to enforce a check on the size of shellOut.txt just as we check for log.txt. What do you think about this @prasadtalasila

**Comment by prasadtalasila** [comment]
This issue is similar to #163. There is nothing we can do except update the imports. Let's push this to later. I suggest closing the issue for now.

**Comment by AnkshitJain** [comment]
We can truncate the shellOut.txt to solve the problem. I have tried it and it is working for this case.

**Comment by AnkshitJain** [comment]
Having something like the code below after line 244  in the file [execute.sh,](https://github.com/AutolabJS/AutolabJS/blob/master/docs/examples/unit_tests/execute.sh#L244) this problem can be solved. 
`````
shellOutLength=$(wc -l shellOut.txt | awk '{print $1}')
if [ "$shellOutLength" -gt 50 ]
then
  head -n 50 shellOut.txt >> temp.txt
  echo -e "\n=====LOG TRUNCATED====\n" >> temp.txt
else
  cp shellOut.txt temp.txt
fi
`````
We can also go in the direction to change the imported modules, but having such big logs doesn't seem to give the users any better advantage.

**Comment by prasadtalasila** [comment]
But the above mentioned code is already part of execute.sh!!

**Comment by AnkshitJain** [comment]
Line [242](https://github.com/AutolabJS/AutolabJS/blob/master/docs/examples/unit_tests/execute.sh#L242)  creates a `log.txt` file. We already have a `shellOut.txt` file at this point. 
Line [246](https://github.com/AutolabJS/AutolabJS/blob/master/docs/examples/unit_tests/execute.sh#L246) moves this `shellOut.txt` to `temp.txt`. 
Lines [249](https://github.com/AutolabJS/AutolabJS/blob/master/docs/examples/unit_tests/execute.sh#L249)-258 take the length of `log.txt`, and if found to be more than 50, these lines truncate them and append it to `temp.txt`. Finally `temp.txt` is moved to `log.txt`.
What happens in the case when `temp.txt` or rather `shellOut.txt` itself is very long? We do not check that and hence the large log file and error in load balancer.


By truncating `shellOut.txt` before going on to `log.txt`, we eliminate the possibility of this kind. This has been verified and found to be working.

**Comment by prasadtalasila** [comment]
PR #261 solves the issue.
