### ISSUE TITLE
Document test structure

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#274]
### Description
The test structure page needs to be split into unit tests, functional tests and deployment tests. We also need an introduction and index on the present test structure page.

Each of the test pages would contain separate section on adding new tests.

**Comment by prasadtalasila** [comment]
Scope for further improvement.

1. Improve the sentence:    
    on [functional tests](https://github.com/AutolabJS/AutolabJS/wiki/Functional-Tests) page,    
    "Place this shell script in the shell directory, with the name abc.sh. Remember, the filename for bats file and shell script file, along with the directory names for the data and helper_scripts should be same."

**Comment by prasadtalasila** [comment]
@AnkshitJain 
one suggestion on this work At the end of "writing a new unit test" section of [unit tests](https://github.com/AutolabJS/AutolabJS/wiki/Unit-Tests) page, it would be better to give a directory structure for xyz.js and its unit test. This suggested diagram is similar to the diagram existing at the end of the page on [functional tests](https://github.com/AutolabJS/AutolabJS/wiki/Functional-Tests) page.

**Comment by prasadtalasila** [comment]
@AnkshitJain After you update the unit tests page, you can close this issue.

**Comment by AnkshitJain** [comment]
The page has been updated. Closing the issue.
