### ISSUE TITLE
linting in IDEs

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#276]
### Description
Provide project support for linting in IDEs.

[Description of the issue]
IDEs such as atom, VS code rely on the installed npm packages of the project (for example, ESLint) in order to complete the linting work. If the underlying npm packages are not installed, the IDEs throw up errors.

### Steps to Reproduce

1. Clone a fresh copy of AutolabJS project
2. Open the project in atom IDE
3. Install linter package on atom; for other IDEs install the equivalent package(s).
3. Open `main_server/main_server.js`. The IDE throws up a bunch of errors saying modules do not exist.

**Expected behavior:** [What you expect to happen]
All the files are properly linted

**Actual behavior:** [What actually happens]
Linting done by packages of IDEs depend on node_modules/ directory of all the AutolabJS components.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time atom IDE is run on a fresh clone of AutolabJS code base.

### Additional Information
We can avoid the problem by running the following commands after cloning a fresh copy of AutolabJS.
```shell
npm install --silent --prefix main_server
npm install --silent --prefix main_server/public/js
npm install --silent --prefix load_balancer
npm install --silent --prefix execution_nodes
npm install --silent --prefix util
npm install --silent --prefix tests/deployment_tests
npm install --silent --prefix tests/functional_tests
npm install --silent --prefix tests/test_modules
```

**Comment by prasadtalasila** [comment]
@AnkshitJain can we close this issue?

**Comment by AnkshitJain** [comment]
This issue can be closed. The command to install the dependencies would be 
> bash scripts/npm_install.sh development .
