### ISSUE TITLE
Playbook for installing dependencies

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#288]
### Description
Create a playbook for installing dependencies listed in [dependencies.sh](https://github.com/AutolabJS/AutolabJS/blob/dev/deploy/dependencies.sh)

**Comment by shivin7** [comment]
Sir, I'm not able to find an ansible attribute for the `-y` attribute of the `apt-get` shell command. There's an attribute for `force-yes`, but none I could find for `assume-yes`.

Also, I needed a clarification of these commands :
`sudo apt-get install -y lxc wget bsdtar curl`
`sudo apt-get install -y "linux-image-extra-$(uname -r)"`
I'm guessing we are creating a Linux container for BSDtar package? Why are both `wget` and `curl` used simultaneously?

**Comment by prasadtalasila** [comment]
@shivin7, There seems to be a way to set the default option of apt-get to assume yes for all user required inputs. Please see [tutorial page](https://superuser.com/questions/164553/automatically-answer-yes-when-using-apt-get-install)

**Comment by shivin7** [comment]
Sir, I've created a `dependencies.yml` playbook for all the commands under the `dependencies.sh`.
You can find it under the `depplay` branch of my fork, here :
[https://github.com/shivin7/AutolabJS/blob/depplay/deploy/dependencies.yml](url)

I'm unable to test the playbook, as there's some problem with the installation of AutoLab on my machine. I will get that done and check it ASAP.

Also, I had a doubt : Ansible is itself installed on the remote machine at the end of `dependencies.sh`, but if we are converting it into an Ansible playbook, won't we have to shift that command to some other script which runs before this playbook is supposed to?

**Comment by prasadtalasila** [comment]
@shivin7 There are a few possible corrections in the playbook mentioned by you, but it is ripe for a PR. Please send across a PR to the dev branch and I will suggest some  corrections.

Also, the dependencies.sh does not completely go away. As you mentioned, at least `ansible` and its dependencies need to be installed on the `localhost` machine only by using the shell script. The rest of the work gets done via the dependencies.yml playbook.

**Comment by prasadtalasila** [comment]
PR #293 completes the work.
