### ISSUE TITLE
ansible playbook for setup.sh

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#294]
We need a playbook for replacing [setup.sh](https://github.com/AutolabJS/AutolabJS/blob/dev/deploy/setup.sh). The setup.sh script uses [setup.conf](https://github.com/AutolabJS/AutolabJS/blob/dev/deploy/setup.conf) for reading environment variables. The environment variables are to be read from inventory files, namely [single_machine](https://github.com/AutolabJS/AutolabJS/blob/dev/deploy/single_machine) and [two_machines](https://github.com/AutolabJS/AutolabJS/blob/dev/deploy/two_machines).

@shivin7 you can attempt this issue.

**Comment by shivin7** [comment]
Sir, I've created the playbook.
I'll check the installation on my machine and let you know.

**Comment by prasadtalasila** [comment]
@shivin7 Please open the PR anyway. While you are testing the correctness, I can complete the code review.

**Comment by prasadtalasila** [comment]
PR #301 completes the work.
