### ISSUE TITLE
Mysql behaviour unpredicatable

### ISSUE THREAD

**Issue by AnkshitJain** [AutolabJS/AutolabJS#302]
### Description

Mysql  connection commands fails at two points. The [first](https://github.com/AutolabJS/AutolabJS/blob/dev/deploy/plays/mysqldb.yml#L30) is the installation of Mysql container. The error is 
```
fatal: [mysqldb]: FAILED! => {
    "changed": true, 
    "cmd": [
        "docker", 
        "exec", 
        "autolab-db", 
        "bash", 
        "-c", 
        "mysql -u root -proot -e 'CREATE DATABASE AutolabJS'"
    ], 
    "delta": "0:00:00.296854", 
    "end": "2018-05-11 01:47:54.514807", 
    "rc": 1, 
    "start": "2018-05-11 01:47:54.217953"
}

STDERR:

mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)


MSG:

non-zero return code
```

The [second](https://github.com/AutolabJS/AutolabJS/blob/dev/tests/test_modules/bats/execution_node.bats#L20) failure is in the deployment tests when we run mysql commands to clear the existing database contents. The error is
```
mysql -h 127.0.0.1 -uroot -proot -e "DELETE FROM AutolabJS.llab1;"
ERROR 2026 (HY000): SSL connection error: protocol version mismatch
``` 

### Steps to Reproduce

1. Run the installation
2. Run the deployment tests

**Expected behavior:** [What you expect to happen]
Mysql commands should pass at both points.

**Actual behavior:** [What actually happens]
Mysql commands unpredictably fails at these points.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Sometimes

### Additional Information
The mysql client version was:
```
> mysql --version
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
```
 The mysql image server version is:
```
Server version: 5.7.20-log MySQL Community Server (GPL)
```

**Comment by prasadtalasila** [comment]
@AnkshitJain 
The recommended solution to this problem is specified in this [stackoverflow](https://stackoverflow.com/questions/20751352/suppress-warning-messages-using-mysql-from-within-terminal-but-password-written) thread. It is better to use a mysql.conf file.

**Comment by prasadtalasila** [comment]
The MySQL has been downgraded to v5.7.4. This version has consistent behavior. Please see da72ce2 commit for the changes.
