### ISSUE TITLE
Active connection for SQL database

### ISSUE THREAD

**Issue by AnkshitJain** [AutolabJS/AutolabJS#65]
Only one attempt is currently made for connecting to the database via the load balancer. If the attempt is failed nothing is done to reconnect to the database.  The connection needs to be made repeatedly,in case of failure, and also if it fails multiple times, some error message must be displayed.

**Comment by prasadtalasila** [comment]
When the DB connection is not available, all the evaluation results should lead to a proper error message with the following response.

scores: null
comments: null
log: "Autolab service is down. Please try again later." (encoded in base64 format)

**Comment by AnkshitJain** [comment]
This [file](https://github.com/AutolabJS/AutolabJS/blob/dev/main_server/database.js) needs to be modified, and then can be used for connecting to the database both by main_server and load_balancer. The relevant components in the load_balancer and main_server can then be removed.

**Comment by prasadtalasila** [comment]
Not a priority right now.
