### ISSUE TITLE
ansible uninstall error

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#81]
During uninstall operation, the following error occurs.

```
TASK [Remove executionnode Image] **********************************************    
fatal: [10.1.9.207]: FAILED! => {"changed": false, "failed": true, "msg": "Error removing image execution_node:latest - 409 Client Error: Conflict (\"{\"message\":\"conflict: unable to remove repository reference \\\"execution_node:latest\\\" (must force) - container 30a3e2e9efe9 is using its referenced image 2b52873b876a\"}\")"}    
...ignoring    
```

**Comment by prasadtalasila** [comment]
A more generic version of the problem is that the uninstall script can't and shouldn't remove containers not in the inventory file. In the above case, one extra execution node was created on machine-1 which was using the execution_node container image, thus could not be removed.

The same problem appears in machine-2 because of manual addition of an extra execution node. A good approach would be to take the list of containers from a yaml file (now the list of containers is read from inventory) and proceed with the uninstallation.

When we get to graphical uninstall operation, we can deduce all the execution nodes from load balancer's node_data_conf.json file ask the user for confirmation.

**Comment by prasadtalasila** [comment]
In the recent commits, deploy/keys.sh is executed as part of installation. All the resultant keys generated must also be removed as part of uninstallation setup.

**Comment by prasadtalasila** [comment]
During uninstall process, optionally ask the user for a confirmation to delete the data. The DB and gitlab data of AutolabJS can be removed using the following commands.
```shell
$ sudo rm -rf /opt/sqldata
$ sudo rm -rf /srv/gitlab
```

**Comment by nabidul** [comment]
I solved with force: yes

**Comment by prasadtalasila** [comment]
The [AutolabJS v0.3.0](https://github.com/AutolabJS/AutolabJS/releases/tag/autolab-v0.3.0) has completely configurable installation directory which defaults to `/opt/autolabjs`. All the application data is kept inside this directory and is deleted by `uninstall.yml` playbook. The above mentioned problem of data directories remaining after running of `uninstall.yml` is no longer true.
