### ISSUE TITLE
socket in use exception

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#82]
All the autolab components may be configured to ports that are already in use on a local system. In that case, the containers crash with socket in use error.

We need to catch this exception and log the same in proper format.

**Comment by kashyapgajera** [comment]
There is a try catch sort of thing in ansible. [http://docs.ansible.com/ansible/playbooks_blocks.html] Can we use this?

**Comment by prasadtalasila** [comment]
Not for the socket exceptions. But we do need the ansible playbook blocks feature to remove the installation errors. The playbook blocks feature is going to be certainly useful in resolving #81 and #57 .

**Comment by prasadtalasila** [comment]
Not a priority right now.
