### ISSUE TITLE
HTTPS connection timeout exception

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#84]
At present, there is a latent assumption that all the HTTPS requests either go through or get rejected. A silent dropping of HTTPS requests may happens when we have firewall between any two autolab components.

Hence we need to have a timeout mechanism for each pending HTTPS request. If a request is not satisfied  within specified time out, we can assume the destination to be unavailable. Since such a functionality is useful in all the autolab components, we can have a timeout util function to wrap all HTTPS requests.

**Comment by kashyapgajera** [comment]
req.timeout(time,callback()) already exists. I think we can use that.

**Comment by prasadtalasila** [comment]
Not a priority right now.
