### ISSUE TITLE
Images for socket-io connection

### ISSUE THREAD

**Issue by kashyapgajera** [AutolabJS/AutolabJS#98]
![new doc 8_1](https://cloud.githubusercontent.com/assets/9445462/24085476/f8ebe2b6-0d22-11e7-9c1b-1dcd5f14ef5e.jpg)
![new doc 8_2](https://cloud.githubusercontent.com/assets/9445462/24085477/f970f3e8-0d22-11e7-9787-90d92d91a209.jpg)
![new doc 8_3](https://cloud.githubusercontent.com/assets/9445462/24085478/fb20a0da-0d22-11e7-9b3b-3f54b67943b5.jpg)

**Comment by prasadtalasila** [comment]
work has been preserved on [refactoring](https://github.com/AutolabJS/AutolabJS/wiki/Refactoring-2017) page. Closing the issue.
